//! RL comparison test harness.
//!
//! Each `.rlpr` ground-truth recording becomes a test case (generated by
//! `build.rs`). A case replays the recording through the sim and measures
//! per-tick physics divergence against Rocket League, gates on a per-field
//! percentile budget, reports state-machine mismatch rates, and — on failure
//! or on demand — emits a deep-dive context window.
//!
//! See `how-to-test.md` for the full workflow and the env-var knobs in
//! [`config`].

use crate::rl_comparison_test::recording::Recording;

mod car_order;
mod compare;
mod config;
mod deep_dive;
mod diagnose;
mod measure;
mod recording;
mod report;
mod residual;
mod runner;
mod state;
mod stats;
mod tolerance;

use config::{DeepDiveMode, GateMode, HarnessConfig};

fn test_recording(recording: &Recording) {
    // RLDIAG=1: dump recording events (teleports/demos) instead of measuring.
    if std::env::var("RLDIAG").is_ok() {
        diagnose::dump_events(recording);
        return;
    }

    // RLRESID=1|2: residual-force decomposition (see residual.rs).
    if let Ok(v) = std::env::var("RLRESID") {
        match v.as_str() {
            "1" | "2" => {
                residual::analyze(recording);
                return;
            }
            "3" => {
                residual::analyze_cadence(recording);
                return;
            }
            "4" | "5" | "6" => {
                residual::analyze_impulse(recording);
                return;
            }
            "7" => {
                residual::analyze_impulse_gap(recording);
                return;
            }
            "8" => {
                residual::analyze_car_z(recording);
                return;
            }
            _ => {}
        }
    }

    let cfg = HarnessConfig::from_env();
    let num_cars = recording.info.num_cars as usize;

    // ── Per-tick restore mode (gated physics accuracy, sharded across threads) ──
    let mut report = runner::run_per_tick(recording, &cfg);

    let (outcome, lines) = report::evaluate(&mut report, &cfg);
    for line in &lines {
        println!("{line}");
    }
    if cfg.emit_segments {
        for line in report::segment_lines(&report, &cfg) {
            println!("{line}");
        }
    }
    for line in report::state_lines(&report, &cfg) {
        println!("{line}");
    }

    // ── Continuous mode (informational, opt-in via RLCONT=1) ──
    if cfg.continuous {
        let (mut arena2, car_idcs2) = runner::make_arena(num_cars);
        let cont = runner::run_continuous(recording, &mut arena2, &car_idcs2, &cfg);
        println!(
            "[{}] CONTINUOUS car{}: max_pos={:.2}@t{} max_vel={:.2}@t{} ticks={}",
            recording.name,
            cfg.car_focus.unwrap_or(0),
            cont.max_pos,
            cont.max_pos_tick,
            cont.max_vel,
            cont.max_vel_tick,
            cont.ticks,
        );
    }

    // ── Deep dive ──
    let do_dive = match cfg.deep_dive {
        DeepDiveMode::Always => true,
        DeepDiveMode::Never => false,
        DeepDiveMode::OnFail => !outcome.passed && cfg.gate == GateMode::Strict,
    };
    if do_dive {
        if let Some(center) = outcome.deep_dive_tick {
            deep_dive::dump_window(recording, &cfg, center, outcome.deep_dive_entity);
        } else {
            println!("[{}] DIVE: no tick data to deep-dive", recording.name);
        }
    }

    // ── Gate ──
    if cfg.gate == GateMode::Strict && !outcome.passed {
        panic!(
            "[{}] physics gate FAILED ({} violation(s)). See the [{}] report lines above.\n\
             Deep-dive: RLDEEP=always RLCAR=<i> cargo test case_{} -- --nocapture\n\
             Measure only (no fail): RLGATE=off cargo test case_{} -- --nocapture",
            recording.name,
            outcome.violations.len(),
            recording.name,
            recording.name,
            recording.name,
        );
    }
}

// Called from each generated test file.
#[allow(unused)]
fn run_comparison_test(name: &str, recording_bytes: &[u8]) {
    if !rocketsim::is_initialized() {
        rocketsim::init_from_default(true).unwrap();
    }
    let mut recording = Recording::from_bytes(name, recording_bytes).unwrap();
    // Stabilize car identity (logger array order is unreliable); makes
    // index-based restore/compare valid. No-op for 0/1-car recordings.
    car_order::reorder_cars(&mut recording);
    test_recording(&recording);
}

include!(concat!(env!("OUT_DIR"), "/gen_comparison_tests.rs"));
