//! RL comparison test harness.
//!
//! Each `.rlpr` ground-truth recording becomes a test case (generated by
//! `build.rs`). A case replays the recording through the sim and measures
//! per-tick physics divergence against Rocket League, gates on a per-field
//! percentile budget, reports state-machine mismatch rates, and — on failure
//! or on demand — emits a deep-dive context window.
//!
//! See `how-to-test.md` for the full workflow and the env-var knobs in
//! [`config`].

use crate::rl_comparison_test::recording::Recording;
use std::sync::OnceLock;

mod ballcensus;
mod car_order;
mod carcontact;
mod census;
mod compare;
mod config;
#[cfg(feature = "cpp-compare")]
mod cpp_runner;
mod deep_dive;
#[allow(dead_code)]
mod diagnose;
mod flat_floor;
mod flipdamp;
mod impulse_window;
mod latdump;
mod measure;
mod recording;
mod report;
mod residual;
mod rollout;
mod runner;
mod state;
mod stats;
mod suspdump;
mod tolerance;
mod touchdown;
mod validate;

use config::{DeepDiveMode, GateMode, HarnessConfig};

fn test_recording(recording: &Recording) {
    // Reject ground truth the sim cannot legitimately be graded against, before
    // any measurement path runs. RLNOVALIDATE=1 bypasses this while
    // investigating a suspect recording.
    if !matches!(
        std::env::var("RLNOVALIDATE").as_deref(),
        Ok("1") | Ok("true")
    ) {
        validate::assert_usable_ground_truth(recording);
    }

    // RLDIAG=1: dump recording events (teleports/demos) instead of measuring.
    if std::env::var("RLDIAG").is_ok() {
        diagnose::dump_events(recording);
        return;
    }

    // RLCENSUS=1..9: error-mass census by cause (see census.rs).
    if matches!(
        std::env::var("RLCENSUS").as_deref(),
        Ok("1")
            | Ok("2")
            | Ok("3")
            | Ok("4")
            | Ok("5")
            | Ok("6")
            | Ok("7")
            | Ok("8")
            | Ok("9")
            | Ok("10")
            | Ok("true")
    ) {
        census::analyze(recording);
        return;
    }

    // RLSUSPDUMP=1: dump the sim's post-step vel.z on flat-floor steps for
    // the suspension study (see suspdump.rs).
    if std::env::var("RLSUSPDUMP").is_ok() {
        suspdump::analyze(recording);
        return;
    }

    // RLLATDUMP=1: dump the measured lateral friction impulse on flat-floor
    // steps for the wheel friction study (see latdump.rs).
    if std::env::var("RLLATDUMP").is_ok() {
        latdump::analyze(recording);
        return;
    }

    // RLFLIP=1: dump RL's own flip z-damp decision on airborne flip steps.
    if std::env::var("RLFLIP").is_ok() {
        flipdamp::analyze(recording);
        return;
    }

    // RLBALL=1: error-mass census for the ball, by contact cause.
    // RLBALL=2: liveness survey of the ball's world-contact fields.
    // RLBALL=3: per-step dump. See ballcensus.rs.
    match std::env::var("RLBALL").as_deref() {
        Ok("2") => {
            ballcensus::survey(recording);
            return;
        }
        Ok("4") => {
            ballcensus::bounce_study(recording);
            return;
        }
        Ok(_) => {
            ballcensus::analyze(recording);
            return;
        }
        Err(_) => {}
    }

    // RLCARC=1: dump the measured car-car contact impulse on overlapping steps.
    // RLCARC=2: survey intra-tick physics_frame agreement.
    // RLCARC=3: raw per-car dump for a tick range. See carcontact.rs.
    match std::env::var("RLCARC").as_deref() {
        Ok("2") => {
            carcontact::alias_survey(recording);
            return;
        }
        Ok("3") => {
            carcontact::raw_dump(recording);
            return;
        }
        Ok("4") => {
            carcontact::swap_survey(recording);
            return;
        }
        Ok(_) => {
            carcontact::analyze(recording);
            return;
        }
        Err(_) => {}
    }

    // RLTOUCH=1: dump the measured contact impulse on landing-touchdown steps.
    // RLTOUCH=2: survey the `has_world_contact` field. See touchdown.rs.
    match std::env::var("RLTOUCH").as_deref() {
        Ok("2") => {
            touchdown::survey(recording);
            return;
        }
        Ok(_) => {
            touchdown::analyze(recording);
            return;
        }
        Err(_) => {}
    }

    // RLRESID=1|2: residual-force decomposition (see residual.rs).
    if let Ok(v) = std::env::var("RLRESID") {
        match v.as_str() {
            "1" | "2" => {
                residual::analyze(recording);
                return;
            }
            "3" => {
                residual::analyze_cadence(recording);
                return;
            }
            "4" | "5" | "6" => {
                residual::analyze_impulse(recording);
                return;
            }
            "7" => {
                residual::analyze_impulse_gap(recording);
                return;
            }
            "8" => {
                residual::analyze_car_z(recording);
                return;
            }
            "9" => {
                residual::analyze_car_speed(recording);
                return;
            }
            "10" => {
                residual::analyze_boost(recording);
                return;
            }
            _ => {}
        }
    }

    let cfg = HarnessConfig::from_env();
    let num_cars = recording.info.num_cars as usize;

    // ── Per-tick restore mode (gated physics accuracy, sharded across threads) ──
    let mut report = runner::run_per_tick(recording, &cfg);

    let (mut outcome, lines) = report::evaluate(&mut report, &cfg);
    for line in &lines {
        println!("{line}");
    }

    // ── Impulse windows (jump / double jump / flip) ──
    // The per-tick pass skips the two steps around each press because their
    // split is set by an unrecorded sub-frame phase; this measures the impulse
    // over the pair, where that phase cancels, so impulses stay gated.
    let impulse_report = impulse_window::measure_impulses(recording, &cfg);
    for line in impulse_window::impulse_lines(&impulse_report, &cfg) {
        println!("{line}");
    }
    let impulse_violations = impulse_window::violations(&impulse_report, &cfg);
    if !impulse_violations.is_empty() {
        outcome.passed = false;
        outcome.violations.extend(impulse_violations);
    }
    if cfg.emit_segments {
        for line in report::segment_lines(&report, &cfg) {
            println!("{line}");
        }
    }
    for line in report::state_lines(&report, &cfg) {
        println!("{line}");
    }

    // ── C++ RocketSim comparison (on-demand via RLCPP=1, cpp-compare feature) ──
    if cfg.cpp_compare {
        #[cfg(feature = "cpp-compare")]
        {
            let mut cpp_report = cpp_runner::run_cpp_per_tick(recording, &cfg);
            let mut cpp_cfg = cfg.clone();
            cpp_cfg.gate = GateMode::Off;
            cpp_cfg.deep_dive = DeepDiveMode::Never;
            let (_, cpp_lines) = report::evaluate(&mut cpp_report, &cpp_cfg);
            for line in &cpp_lines {
                println!("{line}");
            }
            for line in report::state_lines(&cpp_report, &cpp_cfg) {
                println!("{line}");
            }
            for line in cpp_runner::comparison_lines(&mut report, &mut cpp_report, &cfg) {
                println!("{line}");
            }
            for line in cpp_runner::tail_comparison_lines(&mut report, &mut cpp_report, &cfg) {
                println!("{line}");
            }
            if cfg.direct_compare {
                let direct = cpp_runner::run_direct_compare(recording, &cfg);
                for line in cpp_runner::direct_lines(&direct, &cfg) {
                    println!("{line}");
                }
            }
        }
        #[cfg(not(feature = "cpp-compare"))]
        {
            println!(
                "[{}] RLCPP=1 requires the cpp-compare feature; rebuild with: \
                 cargo test -p rocketsim --features cpp-compare",
                recording.name,
            );
        }
    }

    // ── Rollout mode (RLROLL=1s / 2s / <ticks>): compounding-error growth ──
    if cfg.rollout_ticks > 0 {
        let rollout_report = rollout::run_rollout(recording, &cfg);
        for line in rollout::rollout_lines(&rollout_report, &cfg) {
            println!("{line}");
        }
        #[cfg(feature = "cpp-compare")]
        if cfg.cpp_compare {
            let cpp_rollout = cpp_runner::run_cpp_rollout(recording, &cfg);
            for line in rollout::rollout_lines(&cpp_rollout, &cfg) {
                println!("{line}");
            }
            for line in cpp_runner::rollout_comparison_lines(&rollout_report, &cpp_rollout, &cfg) {
                println!("{line}");
            }
        }
    }

    // ── Continuous mode (informational, opt-in via RLCONT=1) ──
    if cfg.continuous {
        let (mut arena2, car_idcs2) = runner::make_arena(num_cars);
        let cont = runner::run_continuous(recording, &mut arena2, &car_idcs2, &cfg);
        println!(
            "[{}] CONTINUOUS car{}: max_pos={:.2}@t{} max_vel={:.2}@t{} ticks={} | final_err=({:+.1},{:+.1},{:+.1})",
            recording.name,
            cfg.car_focus.unwrap_or(0),
            cont.max_pos,
            cont.max_pos_tick,
            cont.max_vel,
            cont.max_vel_tick,
            cont.ticks,
            cont.final_pos_err.x,
            cont.final_pos_err.y,
            cont.final_pos_err.z,
        );
        if cont.ticks > 0 {
            println!(
                "[{}] CONTINUOUS ball: max_pos={:.2}@t{} max_vel={:.2}@t{}",
                recording.name,
                cont.ball_max_pos,
                cont.ball_max_pos_tick,
                cont.ball_max_vel,
                cont.ball_max_vel_tick,
            );
        }
    }

    // ── Deep dive ──
    let do_dive = match cfg.deep_dive {
        DeepDiveMode::Always => true,
        DeepDiveMode::Never => false,
        DeepDiveMode::OnFail => !outcome.passed && cfg.gate == GateMode::Strict,
    };
    if do_dive {
        if let Some(center) = outcome.deep_dive_tick {
            deep_dive::dump_window(recording, &cfg, center, outcome.deep_dive_entity);
        } else {
            println!("[{}] DIVE: no tick data to deep-dive", recording.name);
        }
    }

    // ── Gate ──
    if cfg.gate == GateMode::Strict && !outcome.passed {
        panic!(
            "[{}] physics gate FAILED ({} violation(s)). See the [{}] report lines above.\n\
             Deep-dive: RLDEEP=always RLCAR=<i> cargo test case_{} -- --nocapture\n\
             Measure only (no fail): RLGATE=off cargo test case_{} -- --nocapture",
            recording.name,
            outcome.violations.len(),
            recording.name,
            recording.name,
            recording.name,
        );
    }
}

// Called from each generated test file.
#[allow(unused)]
fn run_comparison_test(name: &str, recording_bytes: &[u8]) {
    // `is_initialized()` turns true as soon as init starts, but the collision
    // shapes are only written at the very end — so a bare `is_initialized()`
    // check races under multi-threaded test runs. Gate the whole init behind a
    // single OnceLock so exactly one thread runs it and the rest block.
    static ARENA_READY: OnceLock<()> = OnceLock::new();
    ARENA_READY.get_or_init(|| {
        if !rocketsim::is_initialized() {
            rocketsim::init_from_default(true).unwrap();
        }
    });
    let mut recording = Recording::from_bytes(name, recording_bytes).unwrap();
    // Stabilize car identity (logger array order is unreliable); makes
    // index-based restore/compare valid. No-op for 0/1-car recordings.
    car_order::reorder_cars(&mut recording);
    test_recording(&recording);
}

include!(concat!(env!("OUT_DIR"), "/gen_comparison_tests.rs"));
